class LanguageModel {
  final String code;
  final String name;
  final String nativeName;
  final Map<String, dynamic> translations;

  const LanguageModel({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.translations,
  });

  static const Map<String, LanguageModel> supportedLanguages = {
    'pt-BR': LanguageModel(
      code: 'pt-BR',
      name: 'Portuguese (Brazil)',
      nativeName: 'Português (Brasil)',
      translations: {
        'appTitle': 'My First Words',
        'basicNeeds': {
          'hunger': 'Fome',
          'thirst': 'Sede',
          'bathroom': 'Banheiro',
          'sleep': 'Sono',
          'pain': 'Dor',
          'help': 'Ajuda',
          'hunger_level1': 'Fome',
          'hunger_level2': 'Quero comer',
          'hunger_level3': 'Estou com fome, posso comer?',
          'thirst_level1': 'Sede',
          'thirst_level2': 'Quero beber',
          'thirst_level3': 'Estou com sede, posso beber água?',
          'bathroom_level1': 'Banheiro',
          'bathroom_level2': 'Preciso ir ao banheiro',
          'bathroom_level3': 'Preciso ir ao banheiro, por favor',
          'sleep_level1': 'Sono',
          'sleep_level2': 'Quero dormir',
          'sleep_level3': 'Estou com sono, posso dormir?',
          'pain_level1': 'Dor',
          'pain_level2': 'Estou com dor',
          'pain_level3': 'Estou sentindo dor, preciso de ajuda',
          'help_level1': 'Ajuda',
          'help_level2': 'Preciso de ajuda',
          'help_level3': 'Por favor, preciso de ajuda',
        },
        'emotions': {
          'happy': 'Feliz',
          'sad': 'Triste',
          'angry': 'Bravo',
          'scared': 'Com medo',
          'excited': 'Animado',
          'tired': 'Cansado',
          'happy_level1': 'Feliz',
          'happy_level2': 'Estou feliz',
          'happy_level3': 'Estou muito feliz hoje!',
          'sad_level1': 'Triste',
          'sad_level2': 'Estou triste',
          'sad_level3': 'Estou me sentindo triste',
          'angry_level1': 'Bravo',
          'angry_level2': 'Estou bravo',
          'angry_level3': 'Estou muito bravo com isso',
          'scared_level1': 'Com medo',
          'scared_level2': 'Estou com medo',
          'scared_level3': 'Estou com muito medo disso',
          'excited_level1': 'Animado',
          'excited_level2': 'Estou animado',
          'excited_level3': 'Estou muito animado com isso!',
          'tired_level1': 'Cansado',
          'tired_level2': 'Estou cansado',
          'tired_level3': 'Estou muito cansado, preciso descansar',
        },
        'activities': {
          'play': 'Brincar',
          'eat': 'Comer',
          'drink': 'Beber',
          'sleep': 'Dormir',
          'read': 'Ler',
          'draw': 'Desenhar',
          'play_level1': 'Brincar',
          'play_level2': 'Quero brincar',
          'play_level3': 'Posso brincar com você?',
          'eat_level1': 'Comer',
          'eat_level2': 'Quero comer',
          'eat_level3': 'Estou com fome, posso comer?',
          'drink_level1': 'Beber',
          'drink_level2': 'Quero beber',
          'drink_level3': 'Estou com sede, posso beber?',
          'sleep_level1': 'Dormir',
          'sleep_level2': 'Quero dormir',
          'sleep_level3': 'Estou com sono, posso dormir?',
          'read_level1': 'Ler',
          'read_level2': 'Quero ler',
          'read_level3': 'Posso ler um livro?',
          'draw_level1': 'Desenhar',
          'draw_level2': 'Quero desenhar',
          'draw_level3': 'Posso desenhar agora?',
        },
        'social': {
          'hello': 'Olá',
          'goodbye': 'Tchau',
          'please': 'Por favor',
          'thankYou': 'Obrigado',
          'sorry': 'Desculpe',
          'yes': 'Sim',
          'no': 'Não',
          'hello_level1': 'Olá',
          'hello_level2': 'Olá, tudo bem?',
          'hello_level3': 'Olá! Como você está hoje?',
          'goodbye_level1': 'Tchau',
          'goodbye_level2': 'Tchau, até logo',
          'goodbye_level3': 'Tchau! Até a próxima vez',
          'please_level1': 'Por favor',
          'please_level2': 'Por favor, pode me ajudar?',
          'please_level3': 'Por favor, você poderia me ajudar?',
          'thankYou_level1': 'Obrigado',
          'thankYou_level2': 'Obrigado pela ajuda',
          'thankYou_level3': 'Muito obrigado pela sua ajuda!',
          'sorry_level1': 'Desculpe',
          'sorry_level2': 'Desculpe pelo erro',
          'sorry_level3': 'Me desculpe pelo que aconteceu',
          'yes_level1': 'Sim',
          'yes_level2': 'Sim, concordo',
          'yes_level3': 'Sim, eu concordo com você',
          'no_level1': 'Não',
          'no_level2': 'Não, não quero',
          'no_level3': 'Não, eu não quero isso',
        },
        'parentalConfig': {
          'noAudioConfigured': 'Nenhum áudio configurado',
          'goToSettings': 'Vá para as configurações - Configuração Parental para ativar alguns áudios.',
          'level1Title': 'Palavras',
          'level1Desc': 'Palavras simples: "Água", "Comida", "Ajuda"',
          'level2Title': 'Frases Curtas',
          'level2Desc': 'Frases curtas: "Quero água", "Estou com fome"',
          'level3Title': 'Frases Complexas',
          'level3Desc': 'Frases completas: "Eu gostaria de beber água, por favor"',
        },
        'categories': {
          'basicNeeds': 'Necessidades Básicas',
          'emotions': 'Emoções',
          'activities': 'Atividades',
          'social': 'Social',
        },
        'ui': {
          'settings': 'Configurações',
          'darkMode': 'Modo escuro',
          'enableDarkMode': 'Ativar tema escuro',
          'speechRate': 'Velocidade da fala',
          'volume': 'Volume',
          'pitch': 'Tom da voz',
          'voice': 'Voz',
          'testTts': 'Testar TTS',
          'tapToTest': 'Toque para testar as configurações',
          'parentalConfig': 'Configuração Parental',
          'configureAudios': 'Configurar Áudios Disponíveis',
          'configureAudiosDesc': 'Configure quais áudios estarão disponíveis para a criança',
          'version': 'Versão',
          'developer': 'Desenvolvedor',
          'description': 'Descrição',
          'appDescription': 'Aplicativo de comunicação alternativa para crianças autistas',
          'chooseVoice': 'Escolher Voz',
          'preview': 'Prévia',
          'communicationLevel': 'Nível de Comunicação',
          'communicationLevelDesc': 'Defina a complexidade das frases para a criança.',
          'enableAll': 'Habilitar Todos',
          'disableAll': 'Desabilitar Todos',
          'loadingVoices': 'Carregando vozes disponíveis...',
          'noVoices': 'Nenhuma voz disponível',
          'cancel': 'Cancelar',
          'confirm': 'Confirmar',
          'goToSettingsCta': 'Ir para Configurações',
          'skip': 'Pular',
          'appearance': 'Aparência',
          'language': 'Idioma',
          'audioSettings': 'Configurações de Áudio',
          'aboutApp': 'Sobre o App',
          'categories': 'Categorias',
          'configure': 'Configurar',
          'previewSample': 'Olá! Esta é uma prévia da voz.',
          'selectVoiceSubtitle': 'Selecione a voz que o app usará para falar',
          'ttsTest': 'Teste TTS',
          'basicTest': 'Teste Básico',
          'testWithOptions': 'Teste com Opções',
          'languageTest': 'Teste de Idiomas (4 idiomas)',
          'stopSpeech': 'Parar Fala',
          'instructions': 'Instruções:',
          'instruction1': '• Toque nos botões para testar diferentes funcionalidades',
          'instruction2': '• Use o botão "Parar Fala" para interromper o TTS',
          'instruction3': '• Teste 4 idiomas: Português, Inglês, Espanhol e Alemão',
          'instruction4': '• Verifique se o som está funcionando corretamente',
        },
      },
    ),
    'en': LanguageModel(
      code: 'en',
      name: 'English',
      nativeName: 'English',
      translations: {
        'appTitle': 'My First Words',
        'basicNeeds': {
          'hunger': 'Hunger',
          'thirst': 'Thirst',
          'bathroom': 'Bathroom',
          'sleep': 'Sleep',
          'pain': 'Pain',
          'help': 'Help',
          'hunger_level1': 'Hunger',
          'hunger_level2': 'I want to eat',
          'hunger_level3': 'I am hungry, can I eat?',
          'thirst_level1': 'Thirst',
          'thirst_level2': 'I want to drink',
          'thirst_level3': 'I am thirsty, can I drink water?',
          'bathroom_level1': 'Bathroom',
          'bathroom_level2': 'I need to go to the bathroom',
          'bathroom_level3': 'I need to go to the bathroom, please',
          'sleep_level1': 'Sleep',
          'sleep_level2': 'I want to sleep',
          'sleep_level3': 'I am sleepy, can I sleep?',
          'pain_level1': 'Pain',
          'pain_level2': 'I am in pain',
          'pain_level3': 'I am feeling pain, I need help',
          'help_level1': 'Help',
          'help_level2': 'I need help',
          'help_level3': 'Please, I need help',
        },
        'emotions': {
          'happy': 'Happy',
          'sad': 'Sad',
          'angry': 'Angry',
          'scared': 'Scared',
          'excited': 'Excited',
          'tired': 'Tired',
        },
        'activities': {
          'play': 'Play',
          'eat': 'Eat',
          'drink': 'Drink',
          'sleep': 'Sleep',
          'read': 'Read',
          'draw': 'Draw',
        },
        'social': {
          'hello': 'Hello',
          'goodbye': 'Goodbye',
          'please': 'Please',
          'thankYou': 'Thank you',
          'sorry': 'Sorry',
          'yes': 'Yes',
          'no': 'No',
        },
        'parentalConfig': {
          'noAudioConfigured': 'No audio configured',
          'goToSettings': 'Go to settings - Parental Configuration to enable some audios.',
          'level1Title': 'Words',
          'level1Desc': 'Simple words: "Water", "Food", "Help"',
          'level2Title': 'Short Phrases',
          'level2Desc': 'Short phrases: "I want water", "I am hungry"',
          'level3Title': 'Complex Phrases',
          'level3Desc': 'Full phrases: "I would like to drink water, please"',
        },
        'categories': {
          'basicNeeds': 'Basic Needs',
          'emotions': 'Emotions',
          'activities': 'Activities',
          'social': 'Social',
        },
        'ui': {
          'settings': 'Settings',
          'darkMode': 'Dark mode',
          'enableDarkMode': 'Enable dark theme',
          'speechRate': 'Speech rate',
          'volume': 'Volume',
          'pitch': 'Pitch',
          'voice': 'Voice',
          'testTts': 'Test TTS',
          'tapToTest': 'Tap to test settings',
          'parentalConfig': 'Parental Configuration',
          'configureAudios': 'Configure Available Audios',
          'configureAudiosDesc': 'Choose which audios will be available to the child',
          'version': 'Version',
          'developer': 'Developer',
          'description': 'Description',
          'appDescription': 'Alternative communication app for autistic children',
          'chooseVoice': 'Choose Voice',
          'preview': 'Preview',
          'communicationLevel': 'Communication Level',
          'communicationLevelDesc': 'Define sentence complexity for the child.',
          'enableAll': 'Enable All',
          'disableAll': 'Disable All',
          'loadingVoices': 'Loading available voices...',
          'noVoices': 'No voices available',
          'cancel': 'Cancel',
          'confirm': 'Confirm',
          'goToSettingsCta': 'Go to Settings',
          'skip': 'Skip',
          'appearance': 'Appearance',
          'language': 'Language',
          'audioSettings': 'Audio Settings',
          'aboutApp': 'About App',
          'categories': 'Categories',
          'configure': 'Configure',
          'previewSample': 'Hello! This is a voice preview.',
          'selectVoiceSubtitle': 'Select the voice the app will use to speak',
          'ttsTest': 'TTS Test',
          'basicTest': 'Basic Test',
          'testWithOptions': 'Test with Options',
          'languageTest': 'Language Test (4 languages)',
          'stopSpeech': 'Stop Speech',
          'instructions': 'Instructions:',
          'instruction1': '• Tap buttons to test different features',
          'instruction2': '• Use "Stop Speech" button to interrupt TTS',
          'instruction3': '• Test 4 languages: Portuguese, English, Spanish and German',
          'instruction4': '• Check if sound is working correctly',
        },
      },
    ),
    'es': LanguageModel(
      code: 'es',
      name: 'Spanish',
      nativeName: 'Español',
      translations: {
        'appTitle': 'My First Words',
        'basicNeeds': {
          'hunger': 'Hambre',
          'thirst': 'Sed',
          'bathroom': 'Baño',
          'sleep': 'Sueño',
          'pain': 'Dolor',
          'help': 'Ayuda',
          'hunger_level1': 'Hambre',
          'hunger_level2': 'Quiero comer',
          'hunger_level3': 'Tengo hambre, ¿puedo comer?',
          'thirst_level1': 'Sed',
          'thirst_level2': 'Quiero beber',
          'thirst_level3': 'Tengo sed, ¿puedo beber agua?',
          'bathroom_level1': 'Baño',
          'bathroom_level2': 'Necesito ir al baño',
          'bathroom_level3': 'Necesito ir al baño, por favor',
          'sleep_level1': 'Sueño',
          'sleep_level2': 'Quiero dormir',
          'sleep_level3': 'Tengo sueño, ¿puedo dormir?',
          'pain_level1': 'Dolor',
          'pain_level2': 'Me duele',
          'pain_level3': 'Siento dolor, necesito ayuda',
          'help_level1': 'Ayuda',
          'help_level2': 'Necesito ayuda',
          'help_level3': 'Por favor, necesito ayuda',
        },
        'emotions': {
          'happy': 'Feliz',
          'sad': 'Triste',
          'angry': 'Enojado',
          'scared': 'Asustado',
          'excited': 'Emocionado',
          'tired': 'Cansado',
          'happy_level1': 'Feliz',
          'happy_level2': 'Estoy feliz',
          'happy_level3': '¡Estoy muy feliz hoy!',
          'sad_level1': 'Triste',
          'sad_level2': 'Estoy triste',
          'sad_level3': 'Me siento triste',
          'angry_level1': 'Enojado',
          'angry_level2': 'Estoy enojado',
          'angry_level3': 'Estoy muy enojado con esto',
          'scared_level1': 'Asustado',
          'scared_level2': 'Tengo miedo',
          'scared_level3': 'Tengo mucho miedo de esto',
          'excited_level1': 'Emocionado',
          'excited_level2': 'Estoy emocionado',
          'excited_level3': '¡Estoy muy emocionado con esto!',
          'tired_level1': 'Cansado',
          'tired_level2': 'Estoy cansado',
          'tired_level3': 'Estoy muy cansado, necesito descansar',
        },
        'activities': {
          'play': 'Jugar',
          'eat': 'Comer',
          'drink': 'Beber',
          'sleep': 'Dormir',
          'read': 'Leer',
          'draw': 'Dibujar',
          'play_level1': 'Jugar',
          'play_level2': 'Quiero jugar',
          'play_level3': '¿Puedo jugar contigo?',
          'eat_level1': 'Comer',
          'eat_level2': 'Quiero comer',
          'eat_level3': 'Tengo hambre, ¿puedo comer?',
          'drink_level1': 'Beber',
          'drink_level2': 'Quiero beber',
          'drink_level3': 'Tengo sed, ¿puedo beber?',
          'sleep_level1': 'Dormir',
          'sleep_level2': 'Quiero dormir',
          'sleep_level3': 'Tengo sueño, ¿puedo dormir?',
          'read_level1': 'Leer',
          'read_level2': 'Quiero leer',
          'read_level3': '¿Puedo leer un libro?',
          'draw_level1': 'Dibujar',
          'draw_level2': 'Quiero dibujar',
          'draw_level3': '¿Puedo dibujar ahora?',
        },
        'social': {
          'hello': 'Hola',
          'goodbye': 'Adiós',
          'please': 'Por favor',
          'thankYou': 'Gracias',
          'sorry': 'Lo siento',
          'yes': 'Sí',
          'no': 'No',
          'hello_level1': 'Hola',
          'hello_level2': 'Hola, ¿cómo estás?',
          'hello_level3': '¡Hola! ¿Cómo estás hoy?',
          'goodbye_level1': 'Adiós',
          'goodbye_level2': 'Adiós, hasta luego',
          'goodbye_level3': '¡Adiós! Hasta la próxima vez',
          'please_level1': 'Por favor',
          'please_level2': 'Por favor, ¿puedes ayudarme?',
          'please_level3': 'Por favor, ¿podrías ayudarme?',
          'thankYou_level1': 'Gracias',
          'thankYou_level2': 'Gracias por la ayuda',
          'thankYou_level3': '¡Muchas gracias por tu ayuda!',
          'sorry_level1': 'Lo siento',
          'sorry_level2': 'Lo siento por el error',
          'sorry_level3': 'Me disculpo por lo que pasó',
          'yes_level1': 'Sí',
          'yes_level2': 'Sí, estoy de acuerdo',
          'yes_level3': 'Sí, estoy de acuerdo contigo',
          'no_level1': 'No',
          'no_level2': 'No, no quiero',
          'no_level3': 'No, no quiero eso',
        },
        'parentalConfig': {
          'noAudioConfigured': 'No hay audio configurado',
          'goToSettings': 'Ve a la configuración - Configuración Parental para activar algunos audios.',
          'level1Title': 'Palabras',
          'level1Desc': 'Palabras simples: "Agua", "Comida", "Ayuda"',
          'level2Title': 'Frases Cortas',
          'level2Desc': 'Frases cortas: "Quiero agua", "Tengo hambre"',
          'level3Title': 'Frases Complejas',
          'level3Desc': 'Frases completas: "Me gustaría beber agua, por favor"',
        },
        'categories': {
          'basicNeeds': 'Necesidades Básicas',
          'emotions': 'Emociones',
          'activities': 'Actividades',
          'social': 'Social',
        },
        'ui': {
          'settings': 'Configuración',
          'darkMode': 'Modo oscuro',
          'enableDarkMode': 'Activar tema oscuro',
          'speechRate': 'Velocidad del habla',
          'volume': 'Volumen',
          'pitch': 'Tono de voz',
          'testTts': 'Probar TTS',
          'tapToTest': 'Toca para probar la configuración',
          'parentalConfig': 'Configuración Parental',
          'configureAudios': 'Configurar Audios Disponibles',
          'configureAudiosDesc': 'Configura qué audios estarán disponibles para el niño',
          'version': 'Versión',
          'developer': 'Desarrollador',
          'description': 'Descripción',
          'appDescription': 'Aplicación de comunicación alternativa para niños autistas',
          'chooseVoice': 'Elegir Voz',
          'preview': 'Vista previa',
          'communicationLevel': 'Nivel de Comunicación',
          'communicationLevelDesc': 'Define la complejidad de las frases para el niño.',
          'enableAll': 'Habilitar Todos',
          'disableAll': 'Deshabilitar Todos',
          'loadingVoices': 'Cargando voces disponibles...',
          'noVoices': 'No hay voces disponibles',
          'cancel': 'Cancelar',
          'confirm': 'Confirmar',
          'goToSettingsCta': 'Ir a Configuración',
          'skip': 'Saltar',
          'appearance': 'Apariencia',
          'language': 'Idioma',
          'audioSettings': 'Configuración de Audio',
          'aboutApp': 'Acerca de la App',
          'categories': 'Categorías',
          'configure': 'Configurar',
          'previewSample': '¡Hola! Esta es una vista previa de la voz.',
          'selectVoiceSubtitle': 'Selecciona la voz que la app usará para hablar',
          'ttsTest': 'Prueba TTS',
          'basicTest': 'Prueba Básica',
          'testWithOptions': 'Prueba con Opciones',
          'languageTest': 'Prueba de Idiomas (4 idiomas)',
          'stopSpeech': 'Detener Habla',
          'instructions': 'Instrucciones:',
          'instruction1': '• Toca los botones para probar diferentes funcionalidades',
          'instruction2': '• Usa el botón "Detener Habla" para interrumpir el TTS',
          'instruction3': '• Prueba 4 idiomas: Portugués, Inglés, Español y Alemán',
          'instruction4': '• Verifica si el sonido está funcionando correctamente',
        },
      },
    ),
    'de': LanguageModel(
      code: 'de',
      name: 'German',
      nativeName: 'Deutsch',
      translations: {
        'appTitle': 'My First Words',
        'basicNeeds': {
          'hunger': 'Hunger',
          'thirst': 'Durst',
          'bathroom': 'Badezimmer',
          'sleep': 'Schlaf',
          'pain': 'Schmerz',
          'help': 'Hilfe',
          'hunger_level1': 'Hunger',
          'hunger_level2': 'Ich will essen',
          'hunger_level3': 'Ich habe Hunger, kann ich essen?',
          'thirst_level1': 'Durst',
          'thirst_level2': 'Ich will trinken',
          'thirst_level3': 'Ich habe Durst, kann ich Wasser trinken?',
          'bathroom_level1': 'Badezimmer',
          'bathroom_level2': 'Ich muss auf die Toilette',
          'bathroom_level3': 'Ich muss auf die Toilette, bitte',
          'sleep_level1': 'Schlaf',
          'sleep_level2': 'Ich will schlafen',
          'sleep_level3': 'Ich bin müde, kann ich schlafen?',
          'pain_level1': 'Schmerz',
          'pain_level2': 'Ich habe Schmerzen',
          'pain_level3': 'Ich fühle Schmerzen, ich brauche Hilfe',
          'help_level1': 'Hilfe',
          'help_level2': 'Ich brauche Hilfe',
          'help_level3': 'Bitte, ich brauche Hilfe',
        },
        'emotions': {
          'happy': 'Glücklich',
          'sad': 'Traurig',
          'angry': 'Wütend',
          'scared': 'Angst',
          'excited': 'Aufgeregt',
          'tired': 'Müde',
          'happy_level1': 'Glücklich',
          'happy_level2': 'Ich bin glücklich',
          'happy_level3': 'Ich bin heute sehr glücklich!',
          'sad_level1': 'Traurig',
          'sad_level2': 'Ich bin traurig',
          'sad_level3': 'Ich fühle mich traurig',
          'angry_level1': 'Wütend',
          'angry_level2': 'Ich bin wütend',
          'angry_level3': 'Ich bin sehr wütend darüber',
          'scared_level1': 'Angst',
          'scared_level2': 'Ich habe Angst',
          'scared_level3': 'Ich habe große Angst davor',
          'excited_level1': 'Aufgeregt',
          'excited_level2': 'Ich bin aufgeregt',
          'excited_level3': 'Ich bin sehr aufgeregt darüber!',
          'tired_level1': 'Müde',
          'tired_level2': 'Ich bin müde',
          'tired_level3': 'Ich bin sehr müde, ich muss mich ausruhen',
        },
        'activities': {
          'play': 'Spielen',
          'eat': 'Essen',
          'drink': 'Trinken',
          'sleep': 'Schlafen',
          'read': 'Lesen',
          'draw': 'Zeichnen',
          'play_level1': 'Spielen',
          'play_level2': 'Ich will spielen',
          'play_level3': 'Kann ich mit dir spielen?',
          'eat_level1': 'Essen',
          'eat_level2': 'Ich will essen',
          'eat_level3': 'Ich habe Hunger, kann ich essen?',
          'drink_level1': 'Trinken',
          'drink_level2': 'Ich will trinken',
          'drink_level3': 'Ich habe Durst, kann ich trinken?',
          'sleep_level1': 'Schlafen',
          'sleep_level2': 'Ich will schlafen',
          'sleep_level3': 'Ich bin müde, kann ich schlafen?',
          'read_level1': 'Lesen',
          'read_level2': 'Ich will lesen',
          'read_level3': 'Kann ich ein Buch lesen?',
          'draw_level1': 'Zeichnen',
          'draw_level2': 'Ich will zeichnen',
          'draw_level3': 'Kann ich jetzt zeichnen?',
        },
        'social': {
          'hello': 'Hallo',
          'goodbye': 'Auf Wiedersehen',
          'please': 'Bitte',
          'thankYou': 'Danke',
          'sorry': 'Entschuldigung',
          'yes': 'Ja',
          'no': 'Nein',
          'hello_level1': 'Hallo',
          'hello_level2': 'Hallo, wie geht es dir?',
          'hello_level3': 'Hallo! Wie geht es dir heute?',
          'goodbye_level1': 'Auf Wiedersehen',
          'goodbye_level2': 'Auf Wiedersehen, bis später',
          'goodbye_level3': 'Auf Wiedersehen! Bis zum nächsten Mal',
          'please_level1': 'Bitte',
          'please_level2': 'Bitte, kannst du mir helfen?',
          'please_level3': 'Bitte, könntest du mir helfen?',
          'thankYou_level1': 'Danke',
          'thankYou_level2': 'Danke für die Hilfe',
          'thankYou_level3': 'Vielen Dank für deine Hilfe!',
          'sorry_level1': 'Entschuldigung',
          'sorry_level2': 'Entschuldigung für den Fehler',
          'sorry_level3': 'Es tut mir leid für das, was passiert ist',
          'yes_level1': 'Ja',
          'yes_level2': 'Ja, ich stimme zu',
          'yes_level3': 'Ja, ich stimme dir zu',
          'no_level1': 'Nein',
          'no_level2': 'Nein, ich will nicht',
          'no_level3': 'Nein, ich will das nicht',
        },
        'parentalConfig': {
          'noAudioConfigured': 'Kein Audio konfiguriert',
          'goToSettings': 'Gehen Sie zu den Einstellungen - Elternkonfiguration, um einige Audios zu aktivieren.',
          'level1Title': 'Wörter',
          'level1Desc': 'Einfache Wörter: "Wasser", "Essen", "Hilfe"',
          'level2Title': 'Kurze Sätze',
          'level2Desc': 'Kurze Sätze: "Ich will Wasser", "Ich habe Hunger"',
          'level3Title': 'Komplexe Sätze',
          'level3Desc': 'Vollständige Sätze: "Ich möchte bitte Wasser trinken"',
        },
        'categories': {
          'basicNeeds': 'Grundbedürfnisse',
          'emotions': 'Emotionen',
          'activities': 'Aktivitäten',
          'social': 'Sozial',
        },
        'ui': {
          'settings': 'Einstellungen',
          'darkMode': 'Dunkler Modus',
          'enableDarkMode': 'Dunkles Thema aktivieren',
          'speechRate': 'Sprechgeschwindigkeit',
          'volume': 'Lautstärke',
          'pitch': 'Tonhöhe',
          'testTts': 'TTS testen',
          'tapToTest': 'Tippen Sie, um die Einstellungen zu testen',
          'parentalConfig': 'Elternkonfiguration',
          'configureAudios': 'Verfügbare Audios konfigurieren',
          'configureAudiosDesc': 'Konfigurieren Sie, welche Audios für das Kind verfügbar sind',
          'version': 'Version',
          'developer': 'Entwickler',
          'description': 'Beschreibung',
          'appDescription': 'Alternative Kommunikations-App für autistische Kinder',
          'chooseVoice': 'Stimme wählen',
          'preview': 'Vorschau',
          'communicationLevel': 'Kommunikationsniveau',
          'communicationLevelDesc': 'Definieren Sie die Komplexität der Sätze für das Kind.',
          'enableAll': 'Alle aktivieren',
          'disableAll': 'Alle deaktivieren',
          'loadingVoices': 'Verfügbare Stimmen werden geladen...',
          'noVoices': 'Keine Stimmen verfügbar',
          'cancel': 'Abbrechen',
          'confirm': 'Bestätigen',
          'goToSettingsCta': 'Zu den Einstellungen',
          'skip': 'Überspringen',
          'appearance': 'Erscheinungsbild',
          'language': 'Sprache',
          'audioSettings': 'Audio-Einstellungen',
          'aboutApp': 'Über die App',
          'categories': 'Kategorien',
          'configure': 'Konfigurieren',
          'previewSample': 'Hallo! Dies ist eine Stimmvorschau.',
          'selectVoiceSubtitle': 'Wählen Sie die Stimme, die die App zum Sprechen verwenden wird',
          'ttsTest': 'TTS-Test',
          'basicTest': 'Grundtest',
          'testWithOptions': 'Test mit Optionen',
          'languageTest': 'Sprachtest (4 Sprachen)',
          'stopSpeech': 'Sprache stoppen',
          'instructions': 'Anweisungen:',
          'instruction1': '• Tippen Sie auf die Schaltflächen, um verschiedene Funktionen zu testen',
          'instruction2': '• Verwenden Sie die Schaltfläche "Sprache stoppen", um TTS zu unterbrechen',
          'instruction3': '• Testen Sie 4 Sprachen: Portugiesisch, Englisch, Spanisch und Deutsch',
          'instruction4': '• Überprüfen Sie, ob der Ton korrekt funktioniert',
        },
      },
    ),
  };

  String getTranslation(String key) {
    final keys = key.split('.');
    dynamic current = translations;
    
    for (final k in keys) {
      if (current is Map && current.containsKey(k)) {
        current = current[k];
      } else {
        return key; // Fallback to key if translation not found
      }
    }
    
    return current?.toString() ?? key;
  }
}
