class LanguageModel {
  final String code;
  final String name;
  final String nativeName;
  final Map<String, dynamic> translations;

  const LanguageModel({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.translations,
  });

  static const Map<String, LanguageModel> supportedLanguages = {
    'pt-BR': LanguageModel(
      code: 'pt-BR',
      name: 'Portuguese (Brazil)',
      nativeName: 'Português (Brasil)',
      translations: {
        'appTitle': 'My First Words',
        'basicNeeds': {
          'hunger': 'Fome',
          'thirst': 'Sede',
          'bathroom': 'Banheiro',
          'sleep': 'Sono',
          'pain': 'Dor',
          'help': 'Ajuda',
        },
        'emotions': {
          'happy': 'Feliz',
          'sad': 'Triste',
          'angry': 'Bravo',
          'scared': 'Com medo',
          'excited': 'Animado',
          'tired': 'Cansado',
        },
        'activities': {
          'play': 'Brincar',
          'eat': 'Comer',
          'drink': 'Beber',
          'sleep': 'Dormir',
          'read': 'Ler',
          'draw': 'Desenhar',
        },
        'social': {
          'hello': 'Olá',
          'goodbye': 'Tchau',
          'please': 'Por favor',
          'thankYou': 'Obrigado',
          'sorry': 'Desculpe',
          'yes': 'Sim',
          'no': 'Não',
        },
        'parentalConfig': {
          'noAudioConfigured': 'Nenhum áudio configurado',
          'goToSettings': 'Vá para as configurações - Configuração Parental para ativar alguns áudios.',
          'level1Title': 'Palavras',
          'level1Desc': 'Palavras simples: "Água", "Comida", "Ajuda"',
          'level2Title': 'Frases Curtas',
          'level2Desc': 'Frases curtas: "Quero água", "Estou com fome"',
          'level3Title': 'Frases Complexas',
          'level3Desc': 'Frases completas: "Eu gostaria de beber água, por favor"',
        },
        'categories': {
          'basicNeeds': 'Necessidades Básicas',
          'emotions': 'Emoções',
          'activities': 'Atividades',
          'social': 'Social',
        },
        'ui': {
          'settings': 'Configurações',
          'darkMode': 'Modo escuro',
          'enableDarkMode': 'Ativar tema escuro',
          'speechRate': 'Velocidade da fala',
          'volume': 'Volume',
          'pitch': 'Tom da voz',
          'voice': 'Voz',
          'testTts': 'Testar TTS',
          'tapToTest': 'Toque para testar as configurações',
          'parentalConfig': 'Configuração Parental',
          'configureAudios': 'Configurar Áudios Disponíveis',
          'configureAudiosDesc': 'Configure quais áudios estarão disponíveis para a criança',
          'version': 'Versão',
          'developer': 'Desenvolvedor',
          'description': 'Descrição',
          'appDescription': 'Aplicativo de comunicação alternativa para crianças autistas',
          'chooseVoice': 'Escolher Voz',
          'preview': 'Prévia',
          'communicationLevel': 'Nível de Comunicação',
          'communicationLevelDesc': 'Defina a complexidade das frases para a criança.',
          'enableAll': 'Habilitar Todos',
          'disableAll': 'Desabilitar Todos',
          'loadingVoices': 'Carregando vozes disponíveis...',
          'noVoices': 'Nenhuma voz disponível',
          'cancel': 'Cancelar',
          'confirm': 'Confirmar',
          'goToSettingsCta': 'Ir para Configurações',
          'skip': 'Pular',
          'appearance': 'Aparência',
          'language': 'Idioma',
          'audioSettings': 'Configurações de Áudio',
          'aboutApp': 'Sobre o App',
          'categories': 'Categorias',
          'configure': 'Configurar',
          'previewSample': 'Olá! Esta é uma prévia da voz.',
          'selectVoiceSubtitle': 'Selecione a voz que o app usará para falar',
          'ttsTest': 'Teste TTS',
          'basicTest': 'Teste Básico',
          'testWithOptions': 'Teste com Opções',
          'languageTest': 'Teste de Idiomas (4 idiomas)',
          'stopSpeech': 'Parar Fala',
          'instructions': 'Instruções:',
          'instruction1': '• Toque nos botões para testar diferentes funcionalidades',
          'instruction2': '• Use o botão "Parar Fala" para interromper o TTS',
          'instruction3': '• Teste 4 idiomas: Português, Inglês, Espanhol e Alemão',
          'instruction4': '• Verifique se o som está funcionando corretamente',
        },
      },
    ),
    'en': LanguageModel(
      code: 'en',
      name: 'English',
      nativeName: 'English',
      translations: {
        'appTitle': 'My First Words',
        'basicNeeds': {
          'hunger': 'Hunger',
          'thirst': 'Thirst',
          'bathroom': 'Bathroom',
          'sleep': 'Sleep',
          'pain': 'Pain',
          'help': 'Help',
        },
        'emotions': {
          'happy': 'Happy',
          'sad': 'Sad',
          'angry': 'Angry',
          'scared': 'Scared',
          'excited': 'Excited',
          'tired': 'Tired',
        },
        'activities': {
          'play': 'Play',
          'eat': 'Eat',
          'drink': 'Drink',
          'sleep': 'Sleep',
          'read': 'Read',
          'draw': 'Draw',
        },
        'social': {
          'hello': 'Hello',
          'goodbye': 'Goodbye',
          'please': 'Please',
          'thankYou': 'Thank you',
          'sorry': 'Sorry',
          'yes': 'Yes',
          'no': 'No',
        },
        'parentalConfig': {
          'noAudioConfigured': 'No audio configured',
          'goToSettings': 'Go to settings - Parental Configuration to enable some audios.',
          'level1Title': 'Words',
          'level1Desc': 'Simple words: "Water", "Food", "Help"',
          'level2Title': 'Short Phrases',
          'level2Desc': 'Short phrases: "I want water", "I am hungry"',
          'level3Title': 'Complex Phrases',
          'level3Desc': 'Full phrases: "I would like to drink water, please"',
        },
        'categories': {
          'basicNeeds': 'Basic Needs',
          'emotions': 'Emotions',
          'activities': 'Activities',
          'social': 'Social',
        },
        'ui': {
          'settings': 'Settings',
          'darkMode': 'Dark mode',
          'enableDarkMode': 'Enable dark theme',
          'speechRate': 'Speech rate',
          'volume': 'Volume',
          'pitch': 'Pitch',
          'voice': 'Voice',
          'testTts': 'Test TTS',
          'tapToTest': 'Tap to test settings',
          'parentalConfig': 'Parental Configuration',
          'configureAudios': 'Configure Available Audios',
          'configureAudiosDesc': 'Choose which audios will be available to the child',
          'version': 'Version',
          'developer': 'Developer',
          'description': 'Description',
          'appDescription': 'Alternative communication app for autistic children',
          'chooseVoice': 'Choose Voice',
          'preview': 'Preview',
          'communicationLevel': 'Communication Level',
          'communicationLevelDesc': 'Define sentence complexity for the child.',
          'enableAll': 'Enable All',
          'disableAll': 'Disable All',
          'loadingVoices': 'Loading available voices...',
          'noVoices': 'No voices available',
          'cancel': 'Cancel',
          'confirm': 'Confirm',
          'goToSettingsCta': 'Go to Settings',
          'skip': 'Skip',
          'appearance': 'Appearance',
          'language': 'Language',
          'audioSettings': 'Audio Settings',
          'aboutApp': 'About App',
          'categories': 'Categories',
          'configure': 'Configure',
          'previewSample': 'Hello! This is a voice preview.',
          'selectVoiceSubtitle': 'Select the voice the app will use to speak',
          'ttsTest': 'TTS Test',
          'basicTest': 'Basic Test',
          'testWithOptions': 'Test with Options',
          'languageTest': 'Language Test (4 languages)',
          'stopSpeech': 'Stop Speech',
          'instructions': 'Instructions:',
          'instruction1': '• Tap buttons to test different features',
          'instruction2': '• Use "Stop Speech" button to interrupt TTS',
          'instruction3': '• Test 4 languages: Portuguese, English, Spanish and German',
          'instruction4': '• Check if sound is working correctly',
        },
      },
    ),
    'es': LanguageModel(
      code: 'es',
      name: 'Spanish',
      nativeName: 'Español',
      translations: {
        'appTitle': 'My First Words',
        'basicNeeds': {
          'hunger': 'Hambre',
          'thirst': 'Sed',
          'bathroom': 'Baño',
          'sleep': 'Sueño',
          'pain': 'Dolor',
          'help': 'Ayuda',
        },
        'emotions': {
          'happy': 'Feliz',
          'sad': 'Triste',
          'angry': 'Enojado',
          'scared': 'Asustado',
          'excited': 'Emocionado',
          'tired': 'Cansado',
        },
        'activities': {
          'play': 'Jugar',
          'eat': 'Comer',
          'drink': 'Beber',
          'sleep': 'Dormir',
          'read': 'Leer',
          'draw': 'Dibujar',
        },
        'social': {
          'hello': 'Hola',
          'goodbye': 'Adiós',
          'please': 'Por favor',
          'thankYou': 'Gracias',
          'sorry': 'Lo siento',
          'yes': 'Sí',
          'no': 'No',
        },
        'parentalConfig': {
          'noAudioConfigured': 'No hay audio configurado',
          'goToSettings': 'Ve a la configuración - Configuración Parental para activar algunos audios.',
          'level1Title': 'Palabras',
          'level1Desc': 'Palabras simples: "Agua", "Comida", "Ayuda"',
          'level2Title': 'Frases Cortas',
          'level2Desc': 'Frases cortas: "Quiero agua", "Tengo hambre"',
          'level3Title': 'Frases Complejas',
          'level3Desc': 'Frases completas: "Me gustaría beber agua, por favor"',
        },
        'categories': {
          'basicNeeds': 'Necesidades Básicas',
          'emotions': 'Emociones',
          'activities': 'Actividades',
          'social': 'Social',
        },
        'ui': {
          'settings': 'Configuración',
          'darkMode': 'Modo oscuro',
          'enableDarkMode': 'Activar tema oscuro',
          'speechRate': 'Velocidad del habla',
          'volume': 'Volumen',
          'pitch': 'Tono de voz',
          'testTts': 'Probar TTS',
          'tapToTest': 'Toca para probar la configuración',
          'parentalConfig': 'Configuración Parental',
          'configureAudios': 'Configurar Audios Disponibles',
          'configureAudiosDesc': 'Configura qué audios estarán disponibles para el niño',
          'version': 'Versión',
          'developer': 'Desarrollador',
          'description': 'Descripción',
          'appDescription': 'Aplicación de comunicación alternativa para niños autistas',
          'chooseVoice': 'Elegir Voz',
          'preview': 'Vista previa',
          'communicationLevel': 'Nivel de Comunicación',
          'communicationLevelDesc': 'Define la complejidad de las frases para el niño.',
          'enableAll': 'Habilitar Todos',
          'disableAll': 'Deshabilitar Todos',
          'loadingVoices': 'Cargando voces disponibles...',
          'noVoices': 'No hay voces disponibles',
          'cancel': 'Cancelar',
          'confirm': 'Confirmar',
          'goToSettingsCta': 'Ir a Configuración',
          'skip': 'Saltar',
          'appearance': 'Apariencia',
          'language': 'Idioma',
          'audioSettings': 'Configuración de Audio',
          'aboutApp': 'Acerca de la App',
          'categories': 'Categorías',
          'configure': 'Configurar',
          'previewSample': '¡Hola! Esta es una vista previa de la voz.',
          'selectVoiceSubtitle': 'Selecciona la voz que la app usará para hablar',
          'ttsTest': 'Prueba TTS',
          'basicTest': 'Prueba Básica',
          'testWithOptions': 'Prueba con Opciones',
          'languageTest': 'Prueba de Idiomas (4 idiomas)',
          'stopSpeech': 'Detener Habla',
          'instructions': 'Instrucciones:',
          'instruction1': '• Toca los botones para probar diferentes funcionalidades',
          'instruction2': '• Usa el botón "Detener Habla" para interrumpir el TTS',
          'instruction3': '• Prueba 4 idiomas: Portugués, Inglés, Español y Alemán',
          'instruction4': '• Verifica si el sonido está funcionando correctamente',
        },
      },
    ),
    'de': LanguageModel(
      code: 'de',
      name: 'German',
      nativeName: 'Deutsch',
      translations: {
        'appTitle': 'My First Words',
        'basicNeeds': {
          'hunger': 'Hunger',
          'thirst': 'Durst',
          'bathroom': 'Badezimmer',
          'sleep': 'Schlaf',
          'pain': 'Schmerz',
          'help': 'Hilfe',
        },
        'emotions': {
          'happy': 'Glücklich',
          'sad': 'Traurig',
          'angry': 'Wütend',
          'scared': 'Angst',
          'excited': 'Aufgeregt',
          'tired': 'Müde',
        },
        'activities': {
          'play': 'Spielen',
          'eat': 'Essen',
          'drink': 'Trinken',
          'sleep': 'Schlafen',
          'read': 'Lesen',
          'draw': 'Zeichnen',
        },
        'social': {
          'hello': 'Hallo',
          'goodbye': 'Auf Wiedersehen',
          'please': 'Bitte',
          'thankYou': 'Danke',
          'sorry': 'Entschuldigung',
          'yes': 'Ja',
          'no': 'Nein',
        },
        'parentalConfig': {
          'noAudioConfigured': 'Kein Audio konfiguriert',
          'goToSettings': 'Gehen Sie zu den Einstellungen - Elternkonfiguration, um einige Audios zu aktivieren.',
          'level1Title': 'Wörter',
          'level1Desc': 'Einfache Wörter: "Wasser", "Essen", "Hilfe"',
          'level2Title': 'Kurze Sätze',
          'level2Desc': 'Kurze Sätze: "Ich will Wasser", "Ich habe Hunger"',
          'level3Title': 'Komplexe Sätze',
          'level3Desc': 'Vollständige Sätze: "Ich möchte bitte Wasser trinken"',
        },
        'categories': {
          'basicNeeds': 'Grundbedürfnisse',
          'emotions': 'Emotionen',
          'activities': 'Aktivitäten',
          'social': 'Sozial',
        },
        'ui': {
          'settings': 'Einstellungen',
          'darkMode': 'Dunkler Modus',
          'enableDarkMode': 'Dunkles Thema aktivieren',
          'speechRate': 'Sprechgeschwindigkeit',
          'volume': 'Lautstärke',
          'pitch': 'Tonhöhe',
          'testTts': 'TTS testen',
          'tapToTest': 'Tippen Sie, um die Einstellungen zu testen',
          'parentalConfig': 'Elternkonfiguration',
          'configureAudios': 'Verfügbare Audios konfigurieren',
          'configureAudiosDesc': 'Konfigurieren Sie, welche Audios für das Kind verfügbar sind',
          'version': 'Version',
          'developer': 'Entwickler',
          'description': 'Beschreibung',
          'appDescription': 'Alternative Kommunikations-App für autistische Kinder',
          'chooseVoice': 'Stimme wählen',
          'preview': 'Vorschau',
          'communicationLevel': 'Kommunikationsniveau',
          'communicationLevelDesc': 'Definieren Sie die Komplexität der Sätze für das Kind.',
          'enableAll': 'Alle aktivieren',
          'disableAll': 'Alle deaktivieren',
          'loadingVoices': 'Verfügbare Stimmen werden geladen...',
          'noVoices': 'Keine Stimmen verfügbar',
          'cancel': 'Abbrechen',
          'confirm': 'Bestätigen',
          'goToSettingsCta': 'Zu den Einstellungen',
          'skip': 'Überspringen',
          'appearance': 'Erscheinungsbild',
          'language': 'Sprache',
          'audioSettings': 'Audio-Einstellungen',
          'aboutApp': 'Über die App',
          'categories': 'Kategorien',
          'configure': 'Konfigurieren',
          'previewSample': 'Hallo! Dies ist eine Stimmvorschau.',
          'selectVoiceSubtitle': 'Wählen Sie die Stimme, die die App zum Sprechen verwenden wird',
          'ttsTest': 'TTS-Test',
          'basicTest': 'Grundtest',
          'testWithOptions': 'Test mit Optionen',
          'languageTest': 'Sprachtest (4 Sprachen)',
          'stopSpeech': 'Sprache stoppen',
          'instructions': 'Anweisungen:',
          'instruction1': '• Tippen Sie auf die Schaltflächen, um verschiedene Funktionen zu testen',
          'instruction2': '• Verwenden Sie die Schaltfläche "Sprache stoppen", um TTS zu unterbrechen',
          'instruction3': '• Testen Sie 4 Sprachen: Portugiesisch, Englisch, Spanisch und Deutsch',
          'instruction4': '• Überprüfen Sie, ob der Ton korrekt funktioniert',
        },
      },
    ),
  };

  String getTranslation(String key) {
    final keys = key.split('.');
    dynamic current = translations;
    
    for (final k in keys) {
      if (current is Map && current.containsKey(k)) {
        current = current[k];
      } else {
        return key; // Fallback to key if translation not found
      }
    }
    
    return current?.toString() ?? key;
  }
}
